name: Download M3U8 File

on:
  # 可以设置为手动触发或特定事件触发
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: "M3U8 文件的 URL"
        required: true
        default: "https://example.com/stream.m3u8"
      output_file:
        description: "输出文件名"
        required: false
        default: "downloaded-video.mp4"
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Download M3U8 file
        run: |
          python m3u8_downloader.py --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" --url ${{ github.event.inputs.m3u8_url }} --output ${{ github.event.inputs.output_file }}

      - name: Upload download result
        uses: actions/upload-artifact@v4  # 更新到 v4 版本
        if: success()
        with:
          name: downloaded-file
          path: ${{ github.event.inputs.output_file }}